on: 
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:
      inputs:
        commit:
          description:  'The commit to checkout. Same format as git checkout'
          type: string
          required: true
        checkout-depth:
          description: 'Depth to checkout (default 2)'
          type: number
          required: true
          default: 2

jobs:
  dotnet-deploy:
    runs-on: ubuntu-latest
    if: ${{ ! inputs.commit }}
    name: Deploy a dotnet app
    steps:
      - uses: actions/checkout@v4
      - id: 'check-sha'
        run: git log -1 | head -1 >> commit_info.txt
      - uses: ./.github/composite_actions/deploy
        with:
          ssh_host: ${{ secrets.REMOTE_HOST }}
          ssh_user: ${{ secrets.REMOTE_HOST_USER }}
          ssh_user_key: ${{ secrets.REMOTE_HOST_KEY }}
          source: commit_info.txt
          dst: /opt/deploytest/commit_info
          ssh_cmd: |
            cp /opt/deploytest/commit_info/commit_info.txt /opt/deploytest/info_file.txt
            cat /opt/deploytest/info_file.txt
  revert-deployment:
    runs-on: ubuntu-latest
    if: ${{ inputs.commit }}
    steps:
      - id: 'custom-checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ inputs.checkout-depth}}
      - run: git checkout ${{ inputs.commit }}
      - run: |
          echo "We asked for commit ${{inputs.commit}}. \
          We checked out " >> commit_info.txt
      - id: 'check-sha'
        run: git log -1 | head -1 >> commit_info.txt
      - run: cat commit_info.txt
      - uses: ./.github/composite_actions/deploy
        with:
          ssh_host: ${{ secrets.REMOTE_HOST }}
          ssh_user: ${{ secrets.REMOTE_HOST_USER }}
          ssh_user_key: ${{ secrets.REMOTE_HOST_KEY }}
          source: commit_info.txt
          dst: /opt/deploytest/commit_info
          ssh_cmd: |
            cp /opt/deploytest/commit_info/commit_info.txt /opt/deploytest/info_file.txt
            cat /opt/deploytest/info_file.txt

